image: docker:latest
variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
services:
  - docker:dind

stages:
  - build

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

build-website:
  stage: build
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE:latest" . -f BlizzTrack/Dockerfile
    - docker push "$CI_REGISTRY_IMAGE:latest"
