image: docker:latest
variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  GIT_SUBMODULE_STRATEGY: recursive

services:
  - docker:dind

stages:
  - build

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

build-blizztrack:
  stage: build
  only:
    - main
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE:latest" . -f "./BlizzTrack/Dockerfile"
    - docker push "$CI_REGISTRY_IMAGE:latest"

build-blizzmeta:
  stage: build
  only:
    - main
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE:latest" . -f "./BlizzMeta/Dockerfile"
    - docker push "$CI_REGISTRY_IMAGE:latest"

build-worker:
  stage: build
  only:
    - main
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE/manager:latest" . -f "./Worker/Dockerfile"
    - docker push "$CI_REGISTRY_IMAGE/manager:latest"

build-nofitications:
  stage: build
  only:
    - main
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE/manager:latest" . -f "./Notifications/Dockerfile"
    - docker push "$CI_REGISTRY_IMAGE/manager:latest"